# Generated by Django 2.2.12 on 2020-05-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
                ('summary', models.TextField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
