# Generated by Django 2.2.12 on 2020-05-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='summary',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='alias',
        ),
    ]
