# Generated by Django 2.2.12 on 2020-05-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapi', '0002_auto_20200526_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
